name: Build and Upload Wheel to Release

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - name: Debug Environment Variables
      #   run: |
      #     echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
      #     echo "Repository: $GITHUB_REPOSITORY"
      #     echo "Tag: $GITHUB_REF"
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        